### ISSUE TITLE
If no aliases are available the code crashes.

### ISSUE THREAD

**Issue by jpharvey** [rabarberpie/grit#5]
In substitute_aliases if self.aliases is None then it cant do the for loop.
Changing it to :-
def substitute_aliases(self, string):
        """ Substitutes aliases in the provided string. This is performed using simple text replacements. """
        if self.aliases is not None:
            for alias in self.aliases:
                string = string.replace(alias, self.aliases[alias])
        return string

fixes the problem.

**Comment by rabarberpie** [comment]
Ops, thanks for the finding this missing None check!
